# fly.toml app configuration file generated for greatsmile on 2023-07-30T00:12:41+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "greatsmile"
primary_region = "nrt"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
